In [7]:
import pandas as pd
import numpy as np 
import time 
from keras.models import load_model

test_file = 'data/pems_test.csv'
df = pd.read_csv(test_file, encoding='utf-8').fillna(0)
df = np.array(df)
lstm = load_model("TrafficPrediction/lstm_model.h5")
scale_ = 0.005076142131979695

Using TensorFlow backend.


In [18]:
n = df.shape[0]
lag = 12
for i in range(0, n):
    data = df[i:i+lag]
    flows = data[:, 1]
    print(flows)
    # Transform the data for prediction
    flows = np.asarray(flows)
    flows = np.multiply(flows, scale_)
    flows = np.reshape(flows, (1, lag, 1))

    # Make the prediction
    preds = lstm.predict(flows)
    
    # Inverse transform
    preds = np.divide(preds, scale_)
    print("Predictions : {}".format(preds))
    
    time.sleep(0.25)

[16 10 11 11 6 13 7 2 6 7 4 7]
Predictions : [[0.]]
[10 11 11 6 13 7 2 6 7 4 7 12]
Predictions : [[1.715934]]
[11 11 6 13 7 2 6 7 4 7 12 5]
Predictions : [[1.3144711]]
[11 6 13 7 2 6 7 4 7 12 5 10]
Predictions : [[2.4078324]]
[6 13 7 2 6 7 4 7 12 5 10 10]
Predictions : [[3.569515]]
[13 7 2 6 7 4 7 12 5 10 10 1]
Predictions : [[0.49793613]]
[7 2 6 7 4 7 12 5 10 10 1 6]
Predictions : [[0.]]
[2 6 7 4 7 12 5 10 10 1 6 6]
Predictions : [[0.]]
[6 7 4 7 12 5 10 10 1 6 6 5]
Predictions : [[0.]]
[7 4 7 12 5 10 10 1 6 6 5 3]
Predictions : [[0.]]
[4 7 12 5 10 10 1 6 6 5 3 3]
Predictions : [[0.]]
[7 12 5 10 10 1 6 6 5 3 3 7]
Predictions : [[0.]]
[12 5 10 10 1 6 6 5 3 3 7 5]
Predictions : [[0.]]
[5 10 10 1 6 6 5 3 3 7 5 2]
Predictions : [[0.]]
[10 10 1 6 6 5 3 3 7 5 2 1]
Predictions : [[0.]]
[10 1 6 6 5 3 3 7 5 2 1 1]
Predictions : [[0.]]
[1 6 6 5 3 3 7 5 2 1 1 4]
Predictions : [[0.]]
[6 6 5 3 3 7 5 2 1 1 4 7]
Predictions : [[0.]]
[6 5 3 3 7 5 2 1 1 4 7 4]
Predictions : [[0.]]
[5 3 3 7 5 2 1 1 4 7 

[113 124 115 120 120 95 109 110 117 114 109 110]
Predictions : [[109.23647]]
[124 115 120 120 95 109 110 117 114 109 110 104]
Predictions : [[106.454956]]
[115 120 120 95 109 110 117 114 109 110 104 119]
Predictions : [[110.5662]]
[120 120 95 109 110 117 114 109 110 104 119 105]
Predictions : [[108.56662]]
[120 95 109 110 117 114 109 110 104 119 105 105]
Predictions : [[106.41207]]
[95 109 110 117 114 109 110 104 119 105 105 116]
Predictions : [[109.48867]]
[109 110 117 114 109 110 104 119 105 105 116 97]
Predictions : [[104.497055]]
[110 117 114 109 110 104 119 105 105 116 97 98]
Predictions : [[100.6936]]
[117 114 109 110 104 119 105 105 116 97 98 91]
Predictions : [[95.88048]]
[114 109 110 104 119 105 105 116 97 98 91 104]
Predictions : [[98.097626]]
[109 110 104 119 105 105 116 97 98 91 104 113]
Predictions : [[104.41183]]
[110 104 119 105 105 116 97 98 91 104 113 101]
Predictions : [[104.23931]]
[104 119 105 105 116 97 98 91 104 113 101 120]
Predictions : [[110.69692]]
[119 105 10

KeyboardInterrupt: 