In [1]:
import pandas as pd
import numpy as np
# cities = ['athens', 'east_rancho_dominguez', 'el_segundo', 'long_beach', 'lynwood', 'norwalk', 'redondo', 'wilmington']
cities = ['athens', 'east_rancho_dominguez', 'el_segundo', 'long_beach', 'lynwood', 'wilmington']


In [3]:
for city in cities:
    in_file = '../data/' + city + '/pems_test.csv'
    out_file = '../data/' + city + '/test.csv'
    df = pd.read_csv(in_file)
    cols = ['5 Minutes', 'Flow (Veh/5 Minutes)', 'Speed (mph)']
    df = df[cols]
    df.to_csv(out_file)
    

In [55]:
df = pd.read_csv('../data/' + 'redondo' + '/test.csv', encoding='utf-8').fillna(0)
df = np.array(df)
data = df[0:12]
print(data)
print(data[:,2])
data = df[1]
print(data[2:])

[[0 '3/22/2018 0:15' 115]
 [1 '3/22/2018 0:20' 48]
 [2 '3/22/2018 0:25' 81]
 [3 '3/22/2018 0:30' 73]
 [4 '3/22/2018 0:35' 71]
 [5 '3/22/2018 0:40' 90]
 [6 '3/22/2018 0:45' 46]
 [7 '3/22/2018 0:50' 53]
 [8 '3/22/2018 0:55' 41]
 [9 '3/22/2018 1:00' 81]
 [10 '3/22/2018 1:05' 68]
 [11 '3/22/2018 1:10' 40]]
[115 48 81 73 71 90 46 53 41 81 68 40]
[48]


In [4]:
test_file = '../data/athens/test.csv'
df = pd.read_csv(test_file, encoding='utf-8').fillna(0)

In [5]:
df = np.array(df)
data = df[0:12]
print(data)

[[0 '3/24/2018 6:15' 130 67.6]
 [1 '3/24/2018 6:20' 148 68.0]
 [2 '3/24/2018 6:25' 146 67.9]
 [3 '3/24/2018 6:30' 139 67.9]
 [4 '3/24/2018 6:35' 153 64.8]
 [5 '3/24/2018 6:40' 172 65.2]
 [6 '3/24/2018 6:45' 163 68.5]
 [7 '3/24/2018 6:50' 174 69.9]
 [8 '3/24/2018 6:55' 156 67.6]
 [9 '3/24/2018 7:00' 155 65.2]
 [10 '3/24/2018 7:05' 163 67.1]
 [11 '3/24/2018 7:10' 181 66.3]]


In [6]:
flows = data[:,2]
avg_speeds = data[:,3]
print(flows)
print(avg_speeds)

[130 148 146 139 153 172 163 174 156 155 163 181]
[67.6 68.0 67.9 67.9 64.8 65.2 68.5 69.9 67.6 65.2 67.1 66.3]


In [7]:
avg_speed = np.mean(avg_speeds)
print(avg_speed)

67.16666666666667
