In [1]:
import keras
from keras.models import load_model

path = "/home/ben/git/research/TrafficPrediction/lstm_model.h5"
model = load_model(path)

Using TensorFlow backend.


In [2]:
model.get_config()

[{'class_name': 'LSTM',
  'config': {'name': 'lstm_1',
   'trainable': True,
   'batch_input_shape': (None, 12, 1),
   'dtype': 'float32',
   'return_sequences': True,
   'return_state': False,
   'go_backwards': False,
   'stateful': False,
   'unroll': False,
   'units': 256,
   'activation': 'tanh',
   'recurrent_activation': 'hard_sigmoid',
   'use_bias': True,
   'kernel_initializer': {'class_name': 'VarianceScaling',
    'config': {'scale': 1.0,
     'mode': 'fan_avg',
     'distribution': 'uniform',
     'seed': None}},
   'recurrent_initializer': {'class_name': 'VarianceScaling',
    'config': {'scale': 1.0,
     'mode': 'fan_avg',
     'distribution': 'uniform',
     'seed': None}},
   'bias_initializer': {'class_name': 'Zeros', 'config': {}},
   'unit_forget_bias': True,
   'kernel_regularizer': None,
   'recurrent_regularizer': None,
   'bias_regularizer': None,
   'activity_regularizer': None,
   'kernel_constraint': None,
   'recurrent_constraint': None,
   'bias_constrain

In [3]:
model.get_weights()

[array([[-0.05038153, -0.07825125, -0.02189761, ...,  0.07689615,
         -0.06547388,  0.03604212]], dtype=float32),
 array([[ 0.01885899, -0.00214819,  0.0217442 , ..., -0.02428966,
          0.03875552,  0.04077813],
        [-0.05130472,  0.00446681, -0.04657568, ...,  0.03486394,
          0.06982164,  0.0070746 ],
        [-0.05504781, -0.04394373, -0.02407696, ...,  0.02200411,
         -0.07467949,  0.04193125],
        ...,
        [-0.05442703, -0.02605502,  0.03934914, ...,  0.02453659,
         -0.02975052,  0.03837685],
        [ 0.01264104,  0.0491083 ,  0.01148702, ...,  0.00916757,
         -0.00223295,  0.0305    ],
        [-0.02270579,  0.07436074, -0.06138463, ...,  0.06654058,
          0.04823318, -0.00347513]], dtype=float32),
 array([-0.01103024, -0.0172945 , -0.00917631, ...,  0.01025565,
         0.00244465,  0.00285393], dtype=float32),
 array([[ 0.03756404,  0.06119284,  0.08435184, ..., -0.04129737,
          0.01630954,  0.10586306],
        [-0.01828023,

In [4]:
for layer in model.layers:
    print(layer.get_output_at(0).get_shape().as_list())

[None, None, 256]
[None, 128]
[None, 128]
[None, 64]
[None, 64]
[None, 1]


In [5]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_1 (LSTM)                (None, 12, 256)           264192    
_________________________________________________________________
lstm_2 (LSTM)                (None, 128)               197120    
_________________________________________________________________
dropout_1 (Dropout)          (None, 128)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 64)                8256      
_________________________________________________________________
dropout_2 (Dropout)          (None, 64)                0         
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 65        
Total params: 469,633
Trainable params: 469,633
Non-trainable params: 0
_________________________________________________________________


In [6]:
for l in model.layers:
    print(l.input_shape)

(None, 12, 1)
(None, 12, 256)
(None, 128)
(None, 128)
(None, 64)
(None, 64)


In [15]:
import tensorflow as tf
from tensorflow.python.platform import gfile
import numpy as np

In [16]:
sample_data = "115;48;81;73;71;90;46;53;41;81;68;40;0;17333965039434"
data = sample_data.split(";")
data = data[:-2]
df = np.array(data)
df = df.astype(np.)
print(df)

['115' '48' '81' '73' '71' '90' '46' '53' '41' '81' '68' '40']


In [12]:
GRAPH_PB_PATH = "/home/ben/git/keras_to_tensorflow/keras.pb"
with tf.Session() as sess:
    with gfile.FastGFile(GRAPH_PB_PATH, 'rb') as f:
        graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())
    sess.graph.as_default()
    tf.import_graph_def(graph_def, name='')
    graph_nodes = [n for n in graph_def.node]
    names = []
    for t in graph_nodes:
        names.append(t.name)
    print(names)

['lstm_1_input', 'lstm_1/kernel', 'lstm_1/kernel/read', 'lstm_1/recurrent_kernel', 'lstm_1/recurrent_kernel/read', 'lstm_1/bias', 'lstm_1/bias/read', 'lstm_1/strided_slice/stack', 'lstm_1/strided_slice/stack_1', 'lstm_1/strided_slice/stack_2', 'lstm_1/strided_slice', 'lstm_1/strided_slice_1/stack', 'lstm_1/strided_slice_1/stack_1', 'lstm_1/strided_slice_1/stack_2', 'lstm_1/strided_slice_1', 'lstm_1/strided_slice_2/stack', 'lstm_1/strided_slice_2/stack_1', 'lstm_1/strided_slice_2/stack_2', 'lstm_1/strided_slice_2', 'lstm_1/strided_slice_3/stack', 'lstm_1/strided_slice_3/stack_1', 'lstm_1/strided_slice_3/stack_2', 'lstm_1/strided_slice_3', 'lstm_1/strided_slice_4/stack', 'lstm_1/strided_slice_4/stack_1', 'lstm_1/strided_slice_4/stack_2', 'lstm_1/strided_slice_4', 'lstm_1/strided_slice_5/stack', 'lstm_1/strided_slice_5/stack_1', 'lstm_1/strided_slice_5/stack_2', 'lstm_1/strided_slice_5', 'lstm_1/strided_slice_6/stack', 'lstm_1/strided_slice_6/stack_1', 'lstm_1/strided_slice_6/stack_2', 'l